# Generated by Django 6.0.2 on 2026-02-07 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('work_type', models.CharField(choices=[('INST', 'Instalación'), ('MANT', 'Mantención'), ('DESINST', 'Desinstalación'), ('REPAR', 'Reparación')], default='INST', max_length=10)),
                ('description', models.TextField()),
                ('assigned_by_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_estimated', models.CharField(default='1 Hora 30 Minutos', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'En espera'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado'), ('COMPLETED', 'Completado')], default='PENDING', max_length=10)),
                ('technician_message', models.TextField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('feedback_comment', models.TextField(blank=True, null=True)),
                ('evaluation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
