# Generated by Django 6.0.2 on 2026-02-17 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='work_type',
            field=models.CharField(choices=[('INST', 'Instalación'), ('MANT', 'Mantención'), ('DESINST', 'Desinstalación'), ('REPAR', 'Reparación'), ('BLOQUEO', 'No Disponible / Bloqueado'), ('VACACIONES', 'Vacaciones')], default='INST', max_length=10),
        ),
    ]
